- name: create nginx servers
  hosts: webservers
  become: true
  remote_user: automation

  tasks:
  - include_tasks: roles/ITtools/tasks/deploy-nginx.yml

- name: copy CA to webservers
  hosts: webservers
  become: true
  remote_user: automation

  tasks:
  - include_tasks: roles/ITtools/tasks/setup-ca.yml 
