- name: Copy certificate file with owner and permissions
  ansible.builtin.copy:
    src: ../files/ilove.crt
    dest: /etc/pki/ca-trust/source/anchors/ca-cert.crt
    mode: '0644'


- name: Copy key file with owner and permissions
  ansible.builtin.copy:
    src: ../files/ilove.key
    dest: /etc/pki/ca-trust/source/anchors/ca-key.key
    mode: '0644'

- name: Copy conf file
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
